# Site
name: 'VivaVerde'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
# disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /posts/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    ethan:
      name:   Ethan Green
      site:   https://openai.com/
      avatar: assets/images/ethan-green.png
      bio:    Ethan is a tech enthusiast and green living advocate, blending his passion for sustainability with cutting-edge AI insights. His content is a harmony of nature and technology.
      email:  wowthemesnet@gmail.com

    ava:
      name:   Ava Stone
      site:   https://www.perplexity.ai/
      avatar: assets/images/ava-stone.png
      bio:    Ava, merges her expertise in AI with a commitment to a sustainable lifestyle. Her writings offer a unique perspective on eco-friendly living through the lens of advanced technology.
      email:  fakemail@gmail.com
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ethan
      avatar: assets/images/ethan.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]